# Generated by Django 5.0.14 on 2026-05-23 18:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(choices=[('stationery', 'Stationery'), ('it_supplies', 'IT Supplies'), ('hygiene', 'Hygiene'), ('pantry', 'Pantry'), ('misc', 'Miscellaneous')], default='misc', max_length=20)),
                ('default_unit', models.CharField(choices=[('pcs', 'pcs'), ('rolls', 'rolls'), ('kg', 'kg'), ('g', 'g'), ('litres', 'litres'), ('ml', 'ml'), ('boxes', 'boxes'), ('packets', 'packets'), ('dozen', 'dozen'), ('metres', 'metres')], default='pcs', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='department', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission_date', models.DateField(default=django.utils.timezone.localdate)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmissionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('pcs', 'pcs'), ('rolls', 'rolls'), ('kg', 'kg'), ('g', 'g'), ('litres', 'litres'), ('ml', 'ml'), ('boxes', 'boxes'), ('packets', 'packets'), ('dozen', 'dozen'), ('metres', 'metres')], default='pcs', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='requisitions.formsubmission')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='requisitions.item')),
            ],
            options={
                'ordering': ['item__item_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='formsubmission',
            constraint=models.UniqueConstraint(fields=('user', 'submission_date'), name='one_submission_per_user_per_day'),
        ),
        migrations.AlterUniqueTogether(
            name='formsubmissionitem',
            unique_together={('submission', 'item')},
        ),
    ]
